# TODO remove controller_version
{% set kluctl_version = get_var(["args.kluctl_version", "args.controller_version"], "v2.20.4") %}
{% set pull_policy = "Always" if ("-devel" in kluctl_version or "-snapshot" in kluctl_version) else "IfNotPresent" %}

resources:
  - crd.yaml
  - manager.yaml
  - rbac.yaml

patches:
  - target:
      kind: Deployment
      name: kluctl-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/kluctl/kluctl:{{ kluctl_version }}
  - target:
      kind: Deployment
      name: kluctl-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: {{ pull_policy }}
{% for a in get_var("args.controller_args", []) %}
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "{{ a }}"
{% endfor %}
{% for a in get_var("args.controller_envs", []) %}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {{ a | to_json }}
{% endfor %}
